#index:
    #path: /
    #defaults: { _controller: 'App\Controller\HelloController::index' }

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh